accelerator: gpu
devices: 2
num_nodes: 1
strategy: ddp
precision: 16-mixed
logger:
  class_path: lightning.pytorch.loggers.WandbLogger
  init_args:
    save_dir: lightning_logs
    project: test
    offline: true
max_epochs: 4
log_every_n_steps: 1
check_val_every_n_epoch: 1
deterministic: true